<?php
$base_url="<?php echo $block->getBaseUrl(); ?>";
?>

<article>
    
        <div class="container-fluid full_grey_bg fab_section">
            <div class="row">
                <h2 class="fab_main_heading">Featured Collections</h2>
                <div class="swiper-container product_slider">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                   <a href="#">  <img src="<?php echo $base_url ?>pub/media/images/featured/happy-to-disturb2.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="free_trial">
                                        <p><span>Free Trial</span>
                                            <img src="<?php echo $base_url ?>pub/media/images/fab_radio/red_blackcart.svg">
                                            <!--<img src="images/fab_radio/clock.svg">-->
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
								
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                   <a href="#">  <img src="<?php echo $base_url ?>pub/media/images/featured/materstroke2.jpg"></a>
                                   <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block" new="true">
                                <span class="new_pro">New</span>
                                <div class="img_box">
								
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                   <a href="#">  <img src="<?php echo $base_url ?>pub/media/images/featured/happy-to-disturb2.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
                                    <a href="#"> <img src="<?php echo $base_url ?>pub/media/images/featured/materstroke2.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                      <div class="swiper-slide">
                            <div class="fab_product_block" new="true">
                                <span class="new_pro">New</span>
                                <div class="img_box">
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
                                   <a href="#"> <img src="<?php echo $base_url ?>pub/media/images/featured/happy-to-disturb2.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid fab_section no_heading">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="fab_single_banner">
                            <a href="#"><img src="<?php echo $base_url ?>pub/media/images/tamil-hits.jpg"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid fab_section pt-0">
            <div class="row">
                <h2 class="fab_main_heading mt-0">Most Popular</h2>
                <div class="swiper-container product_slider most_popu">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
                                    <a href="#"><img src="<?php echo $base_url ?>pub/media/images/most-popular/hansa.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                 <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                    <a href="#"><img src="<?php echo $base_url ?>pub/media/images/most-popular/myth.jpg"></a>
                                   <p>Happy To Disturb</p>
                                </div>
                                 <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                 <a href="#">   <img src="<?php echo $base_url ?>pub/media/images/most-popular/hansa.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                 <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                   <a href="#"> <img src="<?php echo $base_url ?>pub/media/images/most-popular/myth.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
						<div class="swiper-slide">
                            <div class="fab_product_block">
                                <div class="img_box">
                                <span class="fab_wishlish"><i class="fa fa-heart-o"></i></span>
								<img src="<?php echo $base_url ?>pub/media/images/play-icon.svg" class="play">
                                    <a href="#"><img src="<?php echo $base_url ?>pub/media/images/most-popular/hansa.jpg"></a>
                                    <p>Happy To Disturb</p>
                                </div>
                                 <div class="content">
                                    <p><a href="#">I will design 2 modern minimalist logo design 4.9(1k+)</a></p>
                                    <div class="starting">
                                        <p>Starting at <span>$100.99</span> </p>
										<div class="fab_addtocart">
										<tooltip>Add to Cart</tooltip>
										<img src="<?php echo $base_url ?>pub/media/images/fab_radio/redcart.svg">
										</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
					<div class="fab_swiper_btn most_pop_btn_next"><i class="flaticon-right"></i></div>
					<div class="fab_swiper_btn most_pop_btn_prev"><i class="flaticon-left-arrow"></i></div>
                </div>
            </div>
        </div>
        <div class="container-fluid fab_section how_we_work white_content">
            <div class="container">
                <div class="row">
                    <h2 class="fab_main_heading">How We Work</h2>
                    <div class="col-md-7">
                        <div class="fab_main_video">
                            <div class="top">
                                <i class="red"></i>
                                <i class="yellow"></i>
                                <i class="green"></i>
                                <p>http://Feverinternational.com</p>
                            </div>
                            <div class="video_box">
                                <img src="<?php echo $base_url ?>pub/media/images/video_poster.jpg" class="video_bg">
								<iframe id="sml_video" width="100%" height="100%" src="" data-video="https://www.youtube.com/embed/f5dw3nafOuo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
								<span  class="video_play_btn"><img src="<?php echo $base_url ?>pub/media/images/play-icon.svg"></span>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="word_content">
                            <p class="sub_heading top_bar">Exclusive content</p>
                            <p>Discover a curated library created by expert musicians you won’t find anywhere else. content</p>
                            <p class="sub_heading">Fresh tracks</p>
                            <p>Listen to thousands of songs, with more added every day.</p>
                            <a href="#" class="fab_big_btn fab-btn">Get In Touch</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid fab_section no_heading">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="fab_single_banner">
                            <a href="#"><img src="<?php echo $base_url ?>pub/media/images/weekend-class.jpg"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid fab_section fab_client_section half_grey_bg">
            <div class="row">
                <h2 class="fab_main_heading">Our Clients</h2>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="fab_clients">
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/dab.png"></div>
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/radio-relay.png"></div>
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/farm.png"></div>
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/radio-prague.png"></div>
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/gorgeous-fm.png"></div>
                                <div class="client"><img src="<?php echo $base_url ?>pub/media/images/clients/pri.png"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid fab_section">
            <div class="row">
                <h2 class="fab_main_heading">Artists of the Week</h2>

                <div class="col-md-12">
						<div class="fav_artist_block">
                        <div class="fab_artist">
                            <div class="img_block">
                                <img src="<?php echo $base_url ?>pub/media/images/artist/ranveer.jpg">
                            </div>
                            <div class="content_block">
                                <h3>Ranveer Singh</h3>
                                <p>Tanhaji</p>
                                <p><b>Worldwide Release</b></p>
                                <p class="date">10 January 2020</p>
									<div class="content_box">
										<span class="video_btn"><img src="<?php echo $base_url ?>pub/media/images/play-icon.svg"></span>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
									</div>
							</div>
						</div>
                        <div class="fab_artist">
                            <div class="img_block">
                                <img src="<?php echo $base_url ?>pub/media/images/artist/salman.jpg">
                            </div>
                            <div class="content_block">
                                <h3>Salman Khan</h3>
                                <p>Dabangg3</p>
                                <p><b>Worldwide Release</b></p>
                                <p class="date">20 December 2019</p>
									<div class="content_box">
										<span class="video_btn"><img src="<?php echo $base_url ?>pub/media/images/play-icon.svg"></span>
										<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
									</div>
							</div>
						</div>
					</div>
					</div>
			
			</div>
		</div>


		<div class="container-fluid cta_section">
			<div class="row">
				<div class="col-md-12">
					<h2>Everything You Need to Get Creative Projects Done</h2>
					<p>Bring your ideas to life with professional digital assets, resources and services</p>
					<a href="#" class="fab_big_btn red fab-btn">Get Started</a>
				</div>
			</div>
		</div>

        </article>