<?php
/**
 * @author Aitoc Team
 * @copyright Copyright (c) 2019 Aitoc (https://www.aitoc.com)
 * @package Aitoc_TwoFactorAuthentication
 */
?>
<div class="admin__field devclass">
    <label for="otp_password" class="admin__field-label">
        <span><?= $block->escapeHtml(__('One-Time Password')) ?></span>
    </label>
    <div class="admin__field-control">
        <input
            id="otp_password"
            class="admin__control-text admin__field"
            type="password"
            name="<?= $block->escapeHtml(\Aitoc\TwoFactorAuthentication\Helper\Data::LOGIN_FIELD_NAME) ?>" />

        <div class="admin__field-note">
            <span><?= $block->escapeHtml(__('Enter a code from your device or leave the field blank if not configured.')) ?></span>
        </div>
    </div>
</div>
