<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/*
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create();
$collection->setPageSize(4);
$collection->addAttributeToFilter('visibility', '4');
$collection->addAttributeToFilter('artist_of_week', '1');
$collection->addAttributeToSort('update_at', 'DESC');
$collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
$collection->addAttributeToSelect('*')->load();
*/
$collection = $block->getProductCollection();

$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\View');
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');


?>


<div class="container-fluid fab_section">


<div class="row">


<div class="col-md-24">
<div class="fav_artist_block">
<?php
 foreach ($collection as $product) {
	 
				 $imageUrl = $product->getMediaConfig()->getMediaUrl($product->getImage());
			  		$_product = $productRepository->get($product->getSKU());
								
								    $mediaUrl='';
								
									 if ($_product->getExtensionAttributes() && $_product->getExtensionAttributes()->getDownloadableProductSamples()) {
											foreach ($_product->getExtensionAttributes()->getDownloadableProductSamples() as $links) {
												if($links->getSampleUrl()!='')
												{
													$mediaUrl=$links->getSampleUrl();
												}else{
												$mediaUrl= $storeManager->getStore()->getUrl('downloadable/download/sample/', array('sample_id' => $links->getSampleId(), '_secure' => true));
												}
												
												 break;
											}
										}
			  
			  $imageUrl = $product->getMediaConfig()->getMediaUrl($product->getImage());
	 
	 				$artist_name= $product->getResource()->getAttribute('artist_name')->getFrontend()->getValue($product);
	 				$news_from_date= $product->getResource()->getAttribute('news_from_date')->getFrontend()->getValue($product);
                  
	 ?>
<div class="fab_artist">
<div class="img_block img_box pro_img"><img  src="<?php echo $imageUrl?>"></div>
<div class="content_block">
<?php
		 if($artist_name!='')
			{
			 
			 
			 

?>
<h3><?php echo $artist_name;?></h3>
<p><?php echo $product->getName();?>  </p>
<p><strong>Worldwide Release</strong></p>
<p class="date"><?php echo date("d F Y", strtotime($news_from_date));?></p>
<?php
			}
			?>
	
<div class="content_box">
		<?php if( $mediaUrl!='')
					{
									?>
	<span class="video_btn"><img src="pub/media/images/play-icon.svg" class="play play_audio" data-audio="<?php echo $mediaUrl;?>">
	</span>
	<?php
}
	?>
<p><?php echo $product->getShortDescription();?></p>
</div>
</div>
</div>
<!--<div class="fab_artist">
<div class="img_block"><img src="http://www.rupinwadhwa.com/fab2/pub/media/images/artist/salman.jpg"></div>
<div class="content_block">
<h3>Salman Khan</h3>
<p>Dabangg3</p>
<p><strong>Worldwide Release</strong></p>
<p class="date">20 December 2019</p>
<div class="content_box"><span class="video_btn"><img src="http://www.rupinwadhwa.com/fab2/pub/media/images/play-icon.svg"></span>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
</div>
</div>
</div>-->
<?php
 }
	?>
</div>
</div>
</div>

</div>